# Generated by Django 3.1.2 on 2020-10-14 20:30

import HRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('ranking', models.FloatField()),
                ('photo', models.ImageField(blank=True, upload_to=HRM.models.Users.upload_photo)),
                ('resume', models.ImageField(blank=True, upload_to=HRM.models.Users.upload_file)),
            ],
        ),
    ]
